"""
Domain Pydantic Models for Health Tracker Agent.
Strict typing and validation for food items, macro calculations, meal logs, and daily health reports.
"""
from enum import Enum
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field, field_validator


class MealType(str, Enum):
    BREAKFAST = "breakfast"
    LUNCH = "lunch"
    DINNER = "dinner"
    SNACK = "snack"


class FitnessGoal(str, Enum):
    CUTTING = "cutting"       # Weight loss / Fat loss (higher protein, reduced calories)
    BULKING = "bulking"       # Muscle growth (hypertrophy calorie surplus)
    MAINTENANCE = "maintenance" # Weight maintenance & overall health
    ATHLETIC = "athletic"     # High performance endurance/strength


class MacroNutrients(BaseModel):
    """Caloric and macronutrient breakdown values."""
    calories: float = Field(..., description="Total energy content in kilocalories (kcal).")
    protein_g: float = Field(..., description="Protein mass in grams.")
    carbs_g: float = Field(..., description="Total carbohydrate mass in grams.")
    fat_g: float = Field(..., description="Total dietary fat mass in grams.")
    fiber_g: float = Field(0.0, description="Dietary fiber mass in grams.")

    @field_validator("calories", "protein_g", "carbs_g", "fat_g", "fiber_g")
    def round_values(cls, v: float) -> float:
        return round(float(v), 1)


class FoodItem(BaseModel):
    """An individual food item detected or parsed from a meal."""
    name: str = Field(..., description="Human-readable food item name (e.g. 'Poached Egg').")
    quantity: float = Field(1.0, gt=0, description="Amount/serving count of the item.")
    unit: str = Field("serving", description="Unit of measurement (e.g. 'egg', 'g', 'cup', 'slice').")
    macros: MacroNutrients = Field(..., description="Macronutrient content for this portion.")
    confidence_score: float = Field(1.0, ge=0.0, le=1.0, description="Detection confidence score between 0.0 and 1.0.")


class MealLog(BaseModel):
    """Complete record of a logged meal."""
    id: str = Field(..., description="Unique meal log identifier.")
    timestamp: str = Field(..., description="ISO 8601 timestamp string of when meal was consumed.")
    meal_type: MealType = Field(..., description="Category of meal (breakfast, lunch, dinner, snack).")
    input_type: str = Field(..., description="Type of input source: 'text' or 'image'.")
    raw_input: str = Field(..., description="Original raw text prompt or image filename/URL.")
    items: List[FoodItem] = Field(default_factory=list, description="Parsed constituent food items.")
    total_macros: MacroNutrients = Field(..., description="Combined sum of macros for this meal.")
    image_url: Optional[str] = Field(None, description="Path or URL to saved meal image if logged via image.")
    notes: Optional[str] = Field(None, description="User notes or AI processing remarks.")


class UserProfile(BaseModel):
    """User profile details and daily macronutrient target goals."""
    user_id: str = Field(default="user_1", description="User identifier.")
    name: str = Field(default="Alex Rivera", description="Full name.")
    age: int = Field(default=28, ge=1, le=120, description="User age in years.")
    weight_kg: float = Field(default=75.0, gt=0, description="Body weight in kilograms.")
    height_cm: float = Field(default=178.0, gt=0, description="Height in centimeters.")
    fitness_goal: FitnessGoal = Field(default=FitnessGoal.CUTTING, description="Primary fitness objective.")
    
    # Target goals
    daily_calories_target: float = Field(default=2200.0, ge=500, le=10000, description="Target daily energy intake (kcal).")
    daily_protein_target_g: float = Field(default=165.0, ge=20, le=500, description="Target daily protein intake (grams).")
    daily_carbs_target_g: float = Field(default=220.0, ge=10, le=1000, description="Target daily carbohydrate intake (grams).")
    daily_fat_target_g: float = Field(default=65.0, ge=10, le=300, description="Target daily dietary fat intake (grams).")
    daily_fiber_target_g: float = Field(default=30.0, ge=5, le=100, description="Target daily fiber intake (grams).")


class MacroRatio(BaseModel):
    """Distribution percentages of total caloric intake."""
    protein_pct: float = Field(..., ge=0, le=100, description="Percentage of calories from protein (4 kcal/g).")
    carbs_pct: float = Field(..., ge=0, le=100, description="Percentage of calories from carbohydrates (4 kcal/g).")
    fat_pct: float = Field(..., ge=0, le=100, description="Percentage of calories from fat (9 kcal/g).")


class DailyReport(BaseModel):
    """Comprehensive daily report generated by the Daily Report Subagent."""
    report_id: str = Field(..., description="Unique daily report ID.")
    date: str = Field(..., description="Date string (YYYY-MM-DD).")
    user_profile: UserProfile = Field(..., description="User profile and goal targets used for evaluation.")
    total_meals_logged: int = Field(..., ge=0, description="Total count of meals logged today.")
    logged_meals: List[MealLog] = Field(default_factory=list, description="List of all meal logs for the day.")
    
    # Calculated Totals & Progress
    consumed_macros: MacroNutrients = Field(..., description="Total macros consumed across all meals.")
    target_macros: MacroNutrients = Field(..., description="Daily macro goals.")
    remaining_macros: MacroNutrients = Field(..., description="Remaining macro budget for the day (can be negative if exceeded).")
    macro_ratios: MacroRatio = Field(..., description="Caloric percentage breakdown (Protein/Carbs/Fat).")
    
    # Evaluated Insights
    goal_compliance_score: float = Field(..., ge=0, le=100, description="Overall compliance score out of 100%.")
    protein_compliance_pct: float = Field(..., ge=0, description="Percentage of target protein achieved.")
    calorie_compliance_pct: float = Field(..., ge=0, description="Percentage of target calories consumed.")
    
    protein_distribution_by_meal: Dict[str, float] = Field(default_factory=dict, description="Protein intake in grams per meal type.")
    nutritional_insights: List[str] = Field(default_factory=list, description="Actionable insights and dietary advice.")
    report_markdown: str = Field(..., description="Formatted markdown report formatted for export/display.")
